### ISSUE TITLE
Kernel source for 坚果 Pro 2 (Nuts Pro 2)

### ISSUE THREAD

**Issue by ai94iq** [SmartisanTech/SmartisanOS_Kernel_Source#1]
Hello everyone

 i want to get this phone, can you guys please share kernel source so it can be rooted

Thanks

**Comment by txwhjsw** [comment]
👍

**Comment by harryfei** [comment]
> i want to get this phone, can you guys please share kernel source so it can be rooted

Me too.

**Comment by guokainew** [comment]
great!

**Comment by guider** [comment]
this is cool
