### ISSUE TITLE
Missing techpack/audio sources for 坚果R1 / Pro 2S

### ISSUE THREAD

**Issue by xingrz** [SmartisanTech/SmartisanOS_Kernel_Source#10]
贵司开源的坚果 R1 (R1Kernel) 和 Pro 2S (U2Pro-2SKernel) 的内核源码里，缺少了位于 `teckpack/audio` (对应高通仓库路径 `platform/vendor/opensource/audio-kernel`) 下的音频相关模块的源码。

坚果 R1 的 Elliptic 超声波接近传感器依赖该部分的改动才能正常工作，因此可以肯定贵司必然对该部分的源码作了改动。该部分源码和内核一样采用了 GPL v2 协议，同样需要开源。请及时补充。

**Comment by smartisancm** [comment]
teckpack/audio 已经同步开源了。
