### ISSUE TITLE
Pro 2S 源码不完整 / audio-kernel sources for Pro 2S still missing

### ISSUE THREAD

**Issue by xingrz** [SmartisanTech/SmartisanOS_Kernel_Source#14]
@smartisancm 您好，感谢你们在看到 #10 后几时补充了 R1 的 audio-kernel 源码。然而位于 [U2Pro2S-Kernel](https://github.com/SmartisanTech/SmartisanOS_Kernel_Source/tree/U2Pro2S-Kernel/techpack) 分支的 Pro 2S 仍然缺少 `techpack/audio` 目录下的这部分的源码。

重申：audio-kernel 源码和内核一样采用了 GPL v2 协议，同样需要开源。请及时补充。

**Comment by smartisancm** [comment]
感谢关注，已经开源。
